### ISSUE TITLE
Latest version of J1939 Digital Annex may not be compatible with pretty_j1939

### ISSUE THREAD

**Issue by jd-salazar** [nmfta-repo/pretty_1939#32]
I have a file named `J1939DA JAN2022.xlsx` at work. Is this is the same as the Digital Annex mentioned in the HOWTO? 

EDIT: Confirmed it is the same Digital Annex and that the latest version breaks compatibility with ~`pretty_j1939.py`~ `create_j1939db-json.py` due to a library not being able to handle `xlsx` files:

```
C:\Users\JavierSalazar\Documents\komodo_CAN\CAN_Processing\pretty_j1939>py create_j1939db-json.py -f "J1939DA JAN2022.xlsx" -w J1939DA_202201.json
Traceback (most recent call last):
  File "C:\Users\JavierSalazar\Documents\komodo_CAN\CAN_Processing\pretty_j1939\create_j1939db-json.py", line 750, in <module>
    J1939daConverter(all_inputs).convert(args.write_json)
  File "C:\Users\JavierSalazar\Documents\komodo_CAN\CAN_Processing\pretty_j1939\create_j1939db-json.py", line 37, in __init__
    self.digital_annex_xls_list = list(map(lambda da: self.secure_open_workbook(filename=da, on_demand=True),
  File "C:\Users\JavierSalazar\Documents\komodo_CAN\CAN_Processing\pretty_j1939\create_j1939db-json.py", line 37, in <lambda>
    self.digital_annex_xls_list = list(map(lambda da: self.secure_open_workbook(filename=da, on_demand=True),
  File "C:\Users\JavierSalazar\Documents\komodo_CAN\CAN_Processing\pretty_j1939\create_j1939db-json.py", line 43, in secure_open_workbook
    return xlrd.open_workbook(**kwargs)
  File "C:\Users\JavierSalazar\AppData\Local\Programs\Python\Python310\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

**Comment by BenGardiner** [comment]
this was fixed in #36 . thank you for the report, please let us know if you have any other feedback
